# Generated by Django 4.2.8 on 2024-01-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable3',
            old_name='UserID',
            new_name='db_userid',
        ),
    ]
