# Generated by Django 4.2.8 on 2024-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_constantuserdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMonitoringUserContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_userid', models.IntegerField()),
                ('db_container_train', models.IntegerField()),
                ('db_container_auto', models.IntegerField()),
                ('db_container_auto_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMonitoringUserTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_userid', models.IntegerField()),
                ('db_fittingplatform_in', models.IntegerField()),
                ('db_semiwagon_in', models.IntegerField()),
                ('db_auto_in', models.IntegerField()),
                ('db_sea_in', models.IntegerField()),
                ('db_fittingplatform_out', models.IntegerField()),
                ('db_semiwagon_out', models.IntegerField()),
                ('db_auto_out', models.IntegerField()),
                ('db_sea_out', models.IntegerField()),
                ('db_factload', models.IntegerField()),
                ('db_reload', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMonitoringUserWagons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_userid', models.IntegerField()),
                ('db_wagons', models.IntegerField()),
                ('db_wagons_out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMonitoringUserWagonsFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_userid', models.IntegerField()),
                ('db_wagons_fe', models.IntegerField()),
                ('db_wagons_out_fe', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_auto_in',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_auto_out',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_container_auto',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_container_auto_qty',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_container_train',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_factload',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_fittingplatform_in',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_fittingplatform_out',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_reload',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_sea_in',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_sea_out',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_semiwagon_in',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_semiwagon_out',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_wagons',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_wagons_fe',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_wagons_out',
        ),
        migrations.RemoveField(
            model_name='dailymonitoringuserdata',
            name='db_wagons_out_fe',
        ),
    ]
