# Generated by Django 4.2.8 on 2024-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_userid_datatable3_db_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTable2',
        ),
    ]
